<?php

/**
 * @file
 * Displays a warning to logged-in users if the current site is not the live site.
 */

/**
 * Implements hook_init().
 *
 * Checks if CURRENT_ENVIRONMENT is defined. If it is, and it isn't "LIVE", and
 * a user is logged in, set a Drupal message to alert the user that they are
 * working on a site which isn't the live site.
 *
 * @TODO: implement a config page so that we can say which environment is "live".
 */
function greyhead_environment_warning_init() {
  greyhead_environment_warning_define_constants();

  // If we're not on a path with "ajax" in the URL and we're in the wrong
  // environment, Grommit...
  if ((CURRENT_ENVIRONMENT != variable_get('greyhead_environment_warning_live_site', ENVIRONMENT_TYPE_LIVE))
    && (strpos($_GET['q'], 'ajax') === FALSE)) {
    // Hmm, t() around a variable_get for user-submitted data? Not sure about
    // that one...
    $message_html = t(variable_get('greyhead_environment_warning_message', GREYHEAD_ENVIRONMENT_WARNING_DEFAULT_MESSAGE));

    // If the current user can edit this module's settings, add a convenience
    // link.
    if (user_access('administer greyhead environment warning')) {
      $message_html .= ' (' . l(t('Edit this message'), 'admin/config/system/environment-warning') . ')';
    }

    drupal_set_message($message_html, 'warning', FALSE);
  }
}

/**
 * Defines constants for this module.
 */
function greyhead_environment_warning_define_constants() {
  /**
   * Constant definitions.
   */
  defined('ENVIRONMENT_TYPE_LOCAL') || define('ENVIRONMENT_TYPE_LOCAL', 'LOCAL');
  defined('ENVIRONMENT_TYPE_DRUSH') || define('ENVIRONMENT_TYPE_DRUSH', 'DRUSH');
  defined('ENVIRONMENT_TYPE_DEV') || define('ENVIRONMENT_TYPE_DEV', 'DEV');
  defined('ENVIRONMENT_TYPE_RC') || define('ENVIRONMENT_TYPE_RC', 'RC');
  defined('ENVIRONMENT_TYPE_LIVE') || define('ENVIRONMENT_TYPE_LIVE', 'LIVE');
  defined('ENVIRONMENT_TYPE_UNKNOWN') || define('ENVIRONMENT_TYPE_UNKNOWN', 'UNKNOWN');
  defined('SUBENVIRONMENT_TYPE_MAMP') || define('SUBENVIRONMENT_TYPE_MAMP', 'MAMP');

  defined('CURRENT_ENVIRONMENT') || define('CURRENT_ENVIRONMENT', ENVIRONMENT_TYPE_UNKNOWN);
  defined('CURRENT_SUBENVIRONMENT') || define('CURRENT_SUBENVIRONMENT', ENVIRONMENT_TYPE_UNKNOWN);

  define('GREYHEAD_ENVIRONMENT_WARNING_DEFAULT_MESSAGE', 'You\'re viewing a copy of this website which isn\'t the "live" website; any content or settings which you change here may be lost if this site\'s database is replaced with the database from live.');
}

/**
 * Gets an associative array of the available environment types.
 *
 * @return array
 */
function greyhead_environment_warning_get_environment_types() {
  return array(
    ENVIRONMENT_TYPE_LOCAL => ENVIRONMENT_TYPE_LOCAL,
    ENVIRONMENT_TYPE_DRUSH => ENVIRONMENT_TYPE_DRUSH,
    ENVIRONMENT_TYPE_DEV => ENVIRONMENT_TYPE_DEV,
    ENVIRONMENT_TYPE_RC => ENVIRONMENT_TYPE_RC,
    ENVIRONMENT_TYPE_LIVE => ENVIRONMENT_TYPE_LIVE,
    ENVIRONMENT_TYPE_UNKNOWN => ENVIRONMENT_TYPE_UNKNOWN,
  );
}

/**
 * Implements hook_menu().
 */
function greyhead_environment_warning_menu() {
  $items = array();

  $items['admin/config/system/environment-warning'] = array(
    'title' => 'Development environment warning settings',
    'description' => 'Set which type of environment should be considered "live" for this website.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('greyhead_environment_warning_admin'),
    'access arguments' => array('administer greyhead environment warning'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function greyhead_environment_warning_permission() {
  return array(
    'administer greyhead environment warning' => array(
      'title' => t('Administer Greyhead Environment Warning'),
      'description' => t('Set which type of environment should be considered "live" for this website.'),
    ),
  );
}

/**
 * Returns a system settings form.
 *
 * @return mixed
 */
function greyhead_environment_warning_admin() {
  $form = array();

  $form['greyhead_environment_warning_current_site'] = array(
    '#type' => 'item',
    '#title' => t('Current environment'),
    '#markup' => t('The current environment type is detected as @type.', array('@type' => CURRENT_ENVIRONMENT)),
  );

  $form['greyhead_environment_warning_live_site'] = array(
    '#type' => 'select',
    '#title' => t('Which environment should be considered live?'),
    '#description' => t('If you view a copy of this site on a server which isn\'t identified as the live server, a message will be displayed to logged-in users to warn them not to make changes to the database as they may be lost.'),
    '#default_value' => variable_get('greyhead_environment_warning_live_site', ENVIRONMENT_TYPE_LIVE),
    '#options' => greyhead_environment_warning_get_environment_types(),
  );

  $form['greyhead_environment_warning_message'] = array(
    '#type' => 'textfield',
    '#title' => t('What message should be shown on non-live sites?'),
    '#default_value' => variable_get('greyhead_environment_warning_message', GREYHEAD_ENVIRONMENT_WARNING_DEFAULT_MESSAGE),
    '#description' => t('This is the message which will be shown to logged-in users when they are using a non-live site.'),
    '#maxlength' => 255,
  );

  return system_settings_form($form);
}
